dev
ivas1ly/gophermart pull request #5
Opened 2024-02-03 14:20 UTC by ivas1ly

2024-02-08 23:05 UTC, maxlyaptsev requested changes

2024-02-08 23:05 UTC, maxlyaptsev commented on internal/middleware/decompress/gzip.go
> +package decompress
nit 
мидлвары можно объединить с контролером под какой-нибудь api пакет
 - router
 - handlers
 - middlewares

2024-02-10 14:24 UTC, ivas1ly commented on internal/repository/user.go
> +	)
https://github.com/jackc/pgx/blob/5c63f646f820ca9696fc3515c1caf2a557d562e5/rows_test.go#L691

Такая возможность без сторонних библиотек похоже есть только для нескольких значений (для pgx.Rows, здесь же pgx.Row и так не получится).

2024-02-12 14:23 UTC, maxlyaptsev requested changes

2024-02-12 14:23 UTC, maxlyaptsev commented on internal/repository/balance.go
> +	sum int64) error {
```suggestion
func (r *BalanceRepository) AddWithdrawal(ctx context.Context, wd *entities.Withrowal) error {
```

New означает что дальше будет конструктор
Большое количество параметров тяжело читается

2024-02-12 14:23 UTC, maxlyaptsev commented on internal/api/controller/auth/handler.go
> +		r.Post("/register", ah.register)
лучше весь роутер в одном месте хранить - у тебя уже есть пакет router. 
Вообще эту часть обычно генерируют с помощью библиотек которые парсят openapi, например вот - https://github.com/deepmap/oapi-codegen

Поэтому для более простого перехода держать в одном месте удобней. Да и в целом посмотрев на один роутер становится понятно какие ручки обрабатываются

А вот технические ручки (как /ping часто зашивают)

2024-02-12 14:23 UTC, maxlyaptsev commented on internal/api/controller/dto/auth.go
> +package dto
раз для каждой ручки отдельный пакет - кажется удобней было бы держать dto в этих пакетах. т.е. этот файл можно перенести в ../auth/dto.go
Обычно все ручки в одном пакете отдельными файлами - в таком случае делают dto пакет

2024-02-12 14:23 UTC, maxlyaptsev commented on internal/repository/accrual_worker.go
> +			"orders.accrual, orders.created_at, orders.updated_at, orders.deleted_at")
Методы в репозитории всегда выполняют одно конкретное и небольшое действие. Код который в этом методе больше подходит под сервис.
Пример методов в репозитории

- updateOrderByID()
- getOrderByID(id uuid.UUID)
- getOrdersByStatus(status Status)

Важно что внутри делаем только то что сказано в названии. Здесь же вижу серьезный обман - при названии метода GetOrdersToProcess происходит неожиданная модификация данных.

Данные которые используются должны максимально поступать из аргументов - например limit

Что можно сделать: Создать новый сервис/ добавить в существующий подходящий по логике метод который будет объединять действия:

```go
// service/order.go
func prepareOrders() {
  tx := db.Begin()
  orders := repo.GetOrdersByStatus(tx, entity.StatusNew, limit)
  // collect order ids to slice ordersIDs[]
  
  repo.UpdateOrdersToStatus(tx, ordersIDs, entity.StatusProcessing)
  tx.Commit()

  return entity.Orders{
  ...
  }
}


```

2024-02-14 08:36 UTC, maxlyaptsev commented on internal/repository/accrual_worker.go
> +			"orders.accrual, orders.created_at, orders.updated_at, orders.deleted_at")
Ну пока ничего страшного, пусть рядом с репозиторием будет передачи и конекта. А так да, можно сделать подобный пакет для работы с транзакциями - https://habr.com/ru/companies/avito/articles/727168/

2024-02-27 21:26 UTC, merged